<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:date="http://exslt.org/dates-and-times"
                xmlns:doc="http://nwalsh.com/xsl/documentation/1.0"
                exclude-result-prefixes="doc"
                xmlns:exsl="http://exslt.org/common"
                xmlns:str="http://exslt.org/strings"
                extension-element-prefixes="date doc exsl str">
  <!--
$Header: /repo/local.cvs/app/story-xml/src/story5/out-project.xsl,v 1.4 2009/04/03 06:00:13 bruce Exp $
-->
  <xsl:param name="gDraft"
             select="boolean(number('1'))" />
  <xsl:include href="com-param.xsl" />
  <xsl:include href="com-html.xsl" />
  <xsl:include href="com.xsl" />
  <xsl:include href="com-timeline.xsl" />
  <!-- ************************************************** -->
  <xsl:template match="/content">
    <xsl:apply-templates select="book" />
  </xsl:template>
  <!-- ************************************************** -->
  <xsl:template match="book">
    <xsl:call-template name="fTimeline" />
    <xsl:call-template name="fFmtProj" />
  </xsl:template>
  <!-- ******************** -->
  <xsl:template name="fFmtProj">
    <!--
Output the timeline as a OpenProj file (compatable with MS
Project 2003).
Units -> tasks
def-who -> resources
def-where -> resources
def-thread -> resources
-->
    <exsl:document method="xml"
                   href="{concat(@id, '-timeline.proj.xml')}">
      <xsl:apply-templates select="document('/tmp/timeline.xml')"
                           mode="proj" />
    </exsl:document>
  </xsl:template>
  <!-- ******************** -->
  <xsl:template match="timeline"
                mode="proj">
    <xsl:variable name="tDefWhen">
      <xsl:value-of select="concat(def-when/@year, '-', format-number(def-when/@month, '00'), '-', format-number(def-when/@day, '00'), 'T', format-number(def-when/@hour, '00'), ':', format-number(def-when/@min, '00'), ':00')" />
    </xsl:variable>
    <Project xmlns="http://schemas.microsoft.com/project">
      <Name>
        <xsl:value-of select="title/@id" />
      </Name>
      <Title>
        <xsl:value-of select="title/@id" />
      </Title>
      <Manager>
        <xsl:value-of select="concat(author/first-name, ' ', author/surname)" />
      </Manager>
      <ScheduleFromStart>1</ScheduleFromStart>
      <!-- 2008-03-10T08:00:00 -->
      <StartDate>
        <xsl:value-of select="$tDefWhen" />
      </StartDate>
      <FinishDate>
        <xsl:value-of select="$tDefWhen" />
      </FinishDate>
      <FYStartDate>1</FYStartDate>
      <CriticalSlackLimit>0</CriticalSlackLimit>
      <CurrencyDigits>2</CurrencyDigits>
      <CurrencySymbol>$</CurrencySymbol>
      <CurrencySymbolPosition>0</CurrencySymbolPosition>
      <CalendarUID>2</CalendarUID>
      <DefaultStartTime>00:00:00</DefaultStartTime>
      <DefaultFinishTime>09:00:00</DefaultFinishTime>
      <MinutesPerDay>1440</MinutesPerDay>
      <MinutesPerWeek>10080</MinutesPerWeek>
      <DaysPerMonth>30</DaysPerMonth>
      <DefaultTaskType>0</DefaultTaskType>
      <DefaultFixedCostAccrual>2</DefaultFixedCostAccrual>
      <DefaultStandardRate>10</DefaultStandardRate>
      <DefaultOvertimeRate>15</DefaultOvertimeRate>
      <DurationFormat>7</DurationFormat>
      <WorkFormat>2</WorkFormat>
      <EditableActualCosts>0</EditableActualCosts>
      <HonorConstraints>0</HonorConstraints>
      <EarnedValueMethod>0</EarnedValueMethod>
      <InsertedProjectsLikeSummary>0</InsertedProjectsLikeSummary>
      <MultipleCriticalPaths>0</MultipleCriticalPaths>
      <NewTasksEffortDriven>0</NewTasksEffortDriven>
      <NewTasksEstimated>1</NewTasksEstimated>
      <SplitsInProgressTasks>0</SplitsInProgressTasks>
      <SpreadActualCost>0</SpreadActualCost>
      <SpreadPercentComplete>0</SpreadPercentComplete>
      <TaskUpdatesResource>1</TaskUpdatesResource>
      <FiscalYearStart>0</FiscalYearStart>
      <WeekStartDay>1</WeekStartDay>
      <MoveCompletedEndsBack>0</MoveCompletedEndsBack>
      <MoveRemainingStartsBack>0</MoveRemainingStartsBack>
      <MoveRemainingStartsForward>0</MoveRemainingStartsForward>
      <MoveCompletedEndsForward>0</MoveCompletedEndsForward>
      <BaselineForEarnedValue>0</BaselineForEarnedValue>
      <AutoAddNewResourcesAndTasks>1</AutoAddNewResourcesAndTasks>
      <CurrentDate>
        <xsl:value-of select="$tDefWhen" />
      </CurrentDate>
      <MicrosoftProjectServerURL>1</MicrosoftProjectServerURL>
      <Autolink>1</Autolink>
      <NewTaskStartDate>0</NewTaskStartDate>
      <DefaultTaskEVMethod>0</DefaultTaskEVMethod>
      <ProjectExternallyEdited>0</ProjectExternallyEdited>
      <ActualsInSync>0</ActualsInSync>
      <RemoveFileProperties>0</RemoveFileProperties>
      <AdminProject>0</AdminProject>
      <ExtendedAttributes>
        <ExtendedAttribute>
          <FieldID>188743731</FieldID>
          <FieldName>Text1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743734</FieldID>
          <FieldName>Text2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743737</FieldID>
          <FieldName>Text3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743740</FieldID>
          <FieldName>Text4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743743</FieldID>
          <FieldName>Text5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743746</FieldID>
          <FieldName>Text6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743747</FieldID>
          <FieldName>Text7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743748</FieldID>
          <FieldName>Text8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743749</FieldID>
          <FieldName>Text9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743750</FieldID>
          <FieldName>Text10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743997</FieldID>
          <FieldName>Text11</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743998</FieldID>
          <FieldName>Text12</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743999</FieldID>
          <FieldName>Text13</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744000</FieldID>
          <FieldName>Text14</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744001</FieldID>
          <FieldName>Text15</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744002</FieldID>
          <FieldName>Text16</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744003</FieldID>
          <FieldName>Text17</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744004</FieldID>
          <FieldName>Text18</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744005</FieldID>
          <FieldName>Text19</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744006</FieldID>
          <FieldName>Text20</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744007</FieldID>
          <FieldName>Text21</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744008</FieldID>
          <FieldName>Text22</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744009</FieldID>
          <FieldName>Text23</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744010</FieldID>
          <FieldName>Text24</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744011</FieldID>
          <FieldName>Text25</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744012</FieldID>
          <FieldName>Text26</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744013</FieldID>
          <FieldName>Text27</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744014</FieldID>
          <FieldName>Text28</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744015</FieldID>
          <FieldName>Text29</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744016</FieldID>
          <FieldName>Text30</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743732</FieldID>
          <FieldName>Start1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743735</FieldID>
          <FieldName>Start2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743738</FieldID>
          <FieldName>Start3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743741</FieldID>
          <FieldName>Start4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743744</FieldID>
          <FieldName>Start5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743962</FieldID>
          <FieldName>Start6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743964</FieldID>
          <FieldName>Start7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743966</FieldID>
          <FieldName>Start8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743968</FieldID>
          <FieldName>Start9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743970</FieldID>
          <FieldName>Start10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743733</FieldID>
          <FieldName>Finish1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743736</FieldID>
          <FieldName>Finish2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743739</FieldID>
          <FieldName>Finish3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743742</FieldID>
          <FieldName>Finish4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743745</FieldID>
          <FieldName>Finish5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743963</FieldID>
          <FieldName>Finish6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743965</FieldID>
          <FieldName>Finish7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743967</FieldID>
          <FieldName>Finish8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743969</FieldID>
          <FieldName>Finish9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743971</FieldID>
          <FieldName>Finish10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743786</FieldID>
          <FieldName>Cost1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743787</FieldID>
          <FieldName>Cost2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743788</FieldID>
          <FieldName>Cost3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743938</FieldID>
          <FieldName>Cost4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743939</FieldID>
          <FieldName>Cost5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743940</FieldID>
          <FieldName>Cost6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743941</FieldID>
          <FieldName>Cost7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743942</FieldID>
          <FieldName>Cost8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743943</FieldID>
          <FieldName>Cost9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743944</FieldID>
          <FieldName>Cost10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743945</FieldID>
          <FieldName>Date1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743946</FieldID>
          <FieldName>Date2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743947</FieldID>
          <FieldName>Date3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743948</FieldID>
          <FieldName>Date4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743949</FieldID>
          <FieldName>Date5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743950</FieldID>
          <FieldName>Date6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743951</FieldID>
          <FieldName>Date7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743952</FieldID>
          <FieldName>Date8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743953</FieldID>
          <FieldName>Date9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743954</FieldID>
          <FieldName>Date10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743752</FieldID>
          <FieldName>Flag1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743753</FieldID>
          <FieldName>Flag2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743754</FieldID>
          <FieldName>Flag3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743755</FieldID>
          <FieldName>Flag4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743756</FieldID>
          <FieldName>Flag5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743757</FieldID>
          <FieldName>Flag6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743758</FieldID>
          <FieldName>Flag7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743759</FieldID>
          <FieldName>Flag8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743760</FieldID>
          <FieldName>Flag9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743761</FieldID>
          <FieldName>Flag10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743972</FieldID>
          <FieldName>Flag11</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743973</FieldID>
          <FieldName>Flag12</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743974</FieldID>
          <FieldName>Flag13</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743975</FieldID>
          <FieldName>Flag14</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743976</FieldID>
          <FieldName>Flag15</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743977</FieldID>
          <FieldName>Flag16</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743978</FieldID>
          <FieldName>Flag17</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743979</FieldID>
          <FieldName>Flag18</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743980</FieldID>
          <FieldName>Flag19</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743981</FieldID>
          <FieldName>Flag20</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743767</FieldID>
          <FieldName>Number1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743768</FieldID>
          <FieldName>Number2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743769</FieldID>
          <FieldName>Number3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743770</FieldID>
          <FieldName>Number4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743771</FieldID>
          <FieldName>Number5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743982</FieldID>
          <FieldName>Number6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743983</FieldID>
          <FieldName>Number7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743984</FieldID>
          <FieldName>Number8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743985</FieldID>
          <FieldName>Number9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743986</FieldID>
          <FieldName>Number10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743987</FieldID>
          <FieldName>Number11</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743988</FieldID>
          <FieldName>Number12</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743989</FieldID>
          <FieldName>Number13</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743990</FieldID>
          <FieldName>Number14</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743991</FieldID>
          <FieldName>Number15</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743992</FieldID>
          <FieldName>Number16</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743993</FieldID>
          <FieldName>Number17</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743994</FieldID>
          <FieldName>Number18</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743995</FieldID>
          <FieldName>Number19</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743996</FieldID>
          <FieldName>Number20</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743783</FieldID>
          <FieldName>Duration1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743784</FieldID>
          <FieldName>Duration2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743785</FieldID>
          <FieldName>Duration3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743955</FieldID>
          <FieldName>Duration4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743956</FieldID>
          <FieldName>Duration5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743957</FieldID>
          <FieldName>Duration6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743958</FieldID>
          <FieldName>Duration7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743959</FieldID>
          <FieldName>Duration8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743960</FieldID>
          <FieldName>Duration9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188743961</FieldID>
          <FieldName>Duration10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744096</FieldID>
          <FieldName>Outline Code1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744098</FieldID>
          <FieldName>Outline Code2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744100</FieldID>
          <FieldName>Outline Code3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744102</FieldID>
          <FieldName>Outline Code4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744104</FieldID>
          <FieldName>Outline Code5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744106</FieldID>
          <FieldName>Outline Code6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744108</FieldID>
          <FieldName>Outline Code7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744110</FieldID>
          <FieldName>Outline Code8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744112</FieldID>
          <FieldName>Outline Code9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>188744114</FieldID>
          <FieldName>Outline Code10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520904</FieldID>
          <FieldName>Text1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520905</FieldID>
          <FieldName>Text2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520926</FieldID>
          <FieldName>Text3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520927</FieldID>
          <FieldName>Text4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520928</FieldID>
          <FieldName>Text5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520993</FieldID>
          <FieldName>Text6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520994</FieldID>
          <FieldName>Text7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520995</FieldID>
          <FieldName>Text8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520996</FieldID>
          <FieldName>Text9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520997</FieldID>
          <FieldName>Text10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521121</FieldID>
          <FieldName>Text11</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521122</FieldID>
          <FieldName>Text12</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521123</FieldID>
          <FieldName>Text13</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521124</FieldID>
          <FieldName>Text14</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521125</FieldID>
          <FieldName>Text15</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521126</FieldID>
          <FieldName>Text16</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521127</FieldID>
          <FieldName>Text17</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521128</FieldID>
          <FieldName>Text18</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521129</FieldID>
          <FieldName>Text19</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521130</FieldID>
          <FieldName>Text20</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521131</FieldID>
          <FieldName>Text21</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521132</FieldID>
          <FieldName>Text22</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521133</FieldID>
          <FieldName>Text23</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521134</FieldID>
          <FieldName>Text24</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521135</FieldID>
          <FieldName>Text25</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521136</FieldID>
          <FieldName>Text26</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521137</FieldID>
          <FieldName>Text27</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521138</FieldID>
          <FieldName>Text28</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521139</FieldID>
          <FieldName>Text29</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521140</FieldID>
          <FieldName>Text30</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520998</FieldID>
          <FieldName>Start1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205520999</FieldID>
          <FieldName>Start2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521000</FieldID>
          <FieldName>Start3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521001</FieldID>
          <FieldName>Start4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521002</FieldID>
          <FieldName>Start5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521116</FieldID>
          <FieldName>Start6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521117</FieldID>
          <FieldName>Start7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521118</FieldID>
          <FieldName>Start8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521119</FieldID>
          <FieldName>Start9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521120</FieldID>
          <FieldName>Start10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521003</FieldID>
          <FieldName>Finish1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521004</FieldID>
          <FieldName>Finish2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521005</FieldID>
          <FieldName>Finish3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521006</FieldID>
          <FieldName>Finish4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521007</FieldID>
          <FieldName>Finish5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521086</FieldID>
          <FieldName>Finish6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521087</FieldID>
          <FieldName>Finish7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521088</FieldID>
          <FieldName>Finish8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521089</FieldID>
          <FieldName>Finish9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521090</FieldID>
          <FieldName>Finish10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521019</FieldID>
          <FieldName>Cost1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521020</FieldID>
          <FieldName>Cost2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521021</FieldID>
          <FieldName>Cost3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521062</FieldID>
          <FieldName>Cost4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521063</FieldID>
          <FieldName>Cost5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521064</FieldID>
          <FieldName>Cost6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521065</FieldID>
          <FieldName>Cost7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521066</FieldID>
          <FieldName>Cost8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521067</FieldID>
          <FieldName>Cost9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521068</FieldID>
          <FieldName>Cost10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521069</FieldID>
          <FieldName>Date1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521070</FieldID>
          <FieldName>Date2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521071</FieldID>
          <FieldName>Date3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521072</FieldID>
          <FieldName>Date4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521073</FieldID>
          <FieldName>Date5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521074</FieldID>
          <FieldName>Date6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521075</FieldID>
          <FieldName>Date7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521076</FieldID>
          <FieldName>Date8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521077</FieldID>
          <FieldName>Date9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521078</FieldID>
          <FieldName>Date10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521023</FieldID>
          <FieldName>Flag1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521024</FieldID>
          <FieldName>Flag2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521025</FieldID>
          <FieldName>Flag3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521026</FieldID>
          <FieldName>Flag4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521027</FieldID>
          <FieldName>Flag5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521028</FieldID>
          <FieldName>Flag6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521029</FieldID>
          <FieldName>Flag7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521030</FieldID>
          <FieldName>Flag8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521031</FieldID>
          <FieldName>Flag9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521022</FieldID>
          <FieldName>Flag10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521091</FieldID>
          <FieldName>Flag11</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521092</FieldID>
          <FieldName>Flag12</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521093</FieldID>
          <FieldName>Flag13</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521094</FieldID>
          <FieldName>Flag14</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521095</FieldID>
          <FieldName>Flag15</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521096</FieldID>
          <FieldName>Flag16</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521097</FieldID>
          <FieldName>Flag17</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521098</FieldID>
          <FieldName>Flag18</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521099</FieldID>
          <FieldName>Flag19</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521100</FieldID>
          <FieldName>Flag20</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521008</FieldID>
          <FieldName>Number1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521009</FieldID>
          <FieldName>Number2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521010</FieldID>
          <FieldName>Number3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521011</FieldID>
          <FieldName>Number4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521012</FieldID>
          <FieldName>Number5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521101</FieldID>
          <FieldName>Number6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521102</FieldID>
          <FieldName>Number7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521103</FieldID>
          <FieldName>Number8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521104</FieldID>
          <FieldName>Number9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521105</FieldID>
          <FieldName>Number10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521106</FieldID>
          <FieldName>Number11</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521107</FieldID>
          <FieldName>Number12</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521108</FieldID>
          <FieldName>Number13</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521109</FieldID>
          <FieldName>Number14</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521110</FieldID>
          <FieldName>Number15</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521111</FieldID>
          <FieldName>Number16</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521112</FieldID>
          <FieldName>Number17</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521113</FieldID>
          <FieldName>Number18</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521114</FieldID>
          <FieldName>Number19</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521115</FieldID>
          <FieldName>Number20</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521013</FieldID>
          <FieldName>Duration1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521014</FieldID>
          <FieldName>Duration2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521015</FieldID>
          <FieldName>Duration3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521079</FieldID>
          <FieldName>Duration4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521080</FieldID>
          <FieldName>Duration5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521081</FieldID>
          <FieldName>Duration6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521082</FieldID>
          <FieldName>Duration7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521083</FieldID>
          <FieldName>Duration8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521084</FieldID>
          <FieldName>Duration9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521085</FieldID>
          <FieldName>Duration10</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521174</FieldID>
          <FieldName>Outline Code1</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521176</FieldID>
          <FieldName>Outline Code2</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521178</FieldID>
          <FieldName>Outline Code3</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521180</FieldID>
          <FieldName>Outline Code4</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521182</FieldID>
          <FieldName>Outline Code5</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521184</FieldID>
          <FieldName>Outline Code6</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521186</FieldID>
          <FieldName>Outline Code7</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521188</FieldID>
          <FieldName>Outline Code8</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521190</FieldID>
          <FieldName>Outline Code9</FieldName>
        </ExtendedAttribute>
        <ExtendedAttribute>
          <FieldID>205521192</FieldID>
          <FieldName>Outline Code10</FieldName>
        </ExtendedAttribute>
      </ExtendedAttributes>
      <Calendars>
        <Calendar>
          <UID>1</UID>
          <Name>Standard</Name>
          <IsBaseCalendar>1</IsBaseCalendar>
          <WeekDays />
        </Calendar>
        <Calendar>
          <UID>2</UID>
          <Name>24 Hours</Name>
          <IsBaseCalendar>1</IsBaseCalendar>
          <WeekDays>
            <WeekDay>
              <DayType>1</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>2</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>3</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>4</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>5</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>6</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>7</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
          </WeekDays>
        </Calendar>
        <Calendar>
          <UID>3</UID>
          <Name>Night Shift</Name>
          <IsBaseCalendar>1</IsBaseCalendar>
          <WeekDays>
            <WeekDay>
              <DayType>2</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>23:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>3</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>03:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>04:00:00</FromTime>
                  <ToTime>08:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>23:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>4</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>03:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>04:00:00</FromTime>
                  <ToTime>08:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>23:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>5</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>03:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>04:00:00</FromTime>
                  <ToTime>08:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>23:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>6</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>03:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>04:00:00</FromTime>
                  <ToTime>08:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>23:00:00</FromTime>
                  <ToTime>00:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
            <WeekDay>
              <DayType>7</DayType>
              <DayWorking>1</DayWorking>
              <WorkingTimes>
                <WorkingTime>
                  <FromTime>00:00:00</FromTime>
                  <ToTime>03:00:00</ToTime>
                </WorkingTime>
                <WorkingTime>
                  <FromTime>04:00:00</FromTime>
                  <ToTime>08:00:00</ToTime>
                </WorkingTime>
              </WorkingTimes>
            </WeekDay>
          </WeekDays>
        </Calendar>
        <Calendar>
          <UID>4</UID>
          <Name>Resource-Name1</Name>
          <IsBaseCalendar>0</IsBaseCalendar>
          <BaseCalendarUID>2</BaseCalendarUID>
          <WeekDays />
        </Calendar>
        <Calendar>
          <UID>5</UID>
          <Name>Name2</Name>
          <IsBaseCalendar>0</IsBaseCalendar>
          <BaseCalendarUID>2</BaseCalendarUID>
          <WeekDays />
        </Calendar>
      </Calendars>
      <Tasks>
        <xsl:for-each select="record[@r-type='start']">
          <Task>
            <UID>
              <xsl:value-of select="position()" />
            </UID>
            <ID>
              <xsl:value-of select="position()" />
            </ID>
            <Name>
              <xsl:value-of select="substring(concat(@unit, ': ', @title), 1, 30)" />
            </Name>
            <Type>0</Type>
            <IsNull>0</IsNull>
            <CreateDate>
              <xsl:value-of select="$tDefWhen" />
            </CreateDate>
            <WBS />
            <OutlineNumber>1</OutlineNumber>
            <OutlineLevel>1</OutlineLevel>
            <Priority>500</Priority>
            <Start>
              <xsl:value-of select="@u-date" />
            </Start>
            <Finish>
              <xsl:value-of select="@u-end-date" />
            </Finish>
            <Duration>
              <xsl:value-of select="@duration" />
            </Duration>
            <DurationFormat>7</DurationFormat>
            <Work>
              <xsl:value-of select="@duration" />
            </Work>
            <ResumeValid>0</ResumeValid>
            <EffortDriven>1</EffortDriven>
            <Recurring>0</Recurring>
            <OverAllocated>0</OverAllocated>
            <Estimated>0</Estimated>
            <Milestone>0</Milestone>
            <Summary>0</Summary>
            <Critical>1</Critical>
            <IsSubproject>0</IsSubproject>
            <IsSubprojectReadOnly>0</IsSubprojectReadOnly>
            <ExternalTask>0</ExternalTask>
            <StartVariance>0</StartVariance>
            <FinishVariance>0</FinishVariance>
            <WorkVariance>0</WorkVariance>
            <FreeSlack>0</FreeSlack>
            <TotalSlack>0</TotalSlack>
            <FixedCost>0</FixedCost>
            <FixedCostAccrual>3</FixedCostAccrual>
            <Cost>0</Cost>
            <OvertimeCost>0</OvertimeCost>
            <OvertimeWork>PT0H0M0S</OvertimeWork>
            <ActualDuration>PT0H0M0S</ActualDuration>
            <ActualCost>0</ActualCost>
            <ActualOvertimeCost>0</ActualOvertimeCost>
            <ActualWork>PT0H0M0S</ActualWork>
            <ActualOvertimeWork>PT0H0M0S</ActualOvertimeWork>
            <RegularWork>PT0H0M0S</RegularWork>
            <xsl:if test="@type = 'sequel'">
              <RemainingDuration>
                <xsl:value-of select="@duration" />
              </RemainingDuration>
            </xsl:if>
            <xsl:if test="@type = 'scene'">
              <RemainingDuration>
                <xsl:value-of select="'PT0H0M0S'" />
              </RemainingDuration>
            </xsl:if>
            <RemainingCost>0</RemainingCost>
            <RemainingWork>PT0H0M0S</RemainingWork>
            <RemainingOvertimeCost>0</RemainingOvertimeCost>
            <RemainingOvertimeWork>PT0H0M0S</RemainingOvertimeWork>
            <ACWP>0</ACWP>
            <CV>0</CV>
            <ConstraintType>4</ConstraintType>
            <CalendarUID>-1</CalendarUID>
            <ConstraintDate>
              <xsl:value-of select="@u-date" />
            </ConstraintDate>
            <LevelAssignments>0</LevelAssignments>
            <LevelingCanSplit>0</LevelingCanSplit>
            <LevelingDelay>0</LevelingDelay>
            <LevelingDelayFormat>5</LevelingDelayFormat>
            <IgnoreResourceCalendar>0</IgnoreResourceCalendar>
            <Notes>
              <xsl:value-of select="concat(@type, '; when: ', when, '; ', who/@ref, ':who: ', who, '; ', where/@ref, ':where: ', where, '; ', note)" />
            </Notes>
            <HideBar>0</HideBar>
            <Rollup>0</Rollup>
            <BCWS>0</BCWS>
            <BCWP>0</BCWP>
            <EarnedValueMethod>0</EarnedValueMethod>
            <xsl:if test="position() != 1">
              <PredecessorLink>
                <PredecessorUID>
                  <xsl:value-of select="position() - 1" />
                </PredecessorUID>
                <Type>1</Type>
              </PredecessorLink>
            </xsl:if>
            <ActualWorkProtected>PT0H0M0S</ActualWorkProtected>
            <ActualOvertimeWorkProtected>
            PT0H0M0S</ActualOvertimeWorkProtected>
          </Task>
        </xsl:for-each>
      </Tasks>
      <Resources>
        <xsl:for-each select="def-who|def-where|def-thread">
          <Resource>
            <UID>
              <xsl:value-of select="position()" />
            </UID>
            <ID>
              <xsl:value-of select="position()" />
            </ID>
            <Name>
              <xsl:value-of select="@id" />
              <xsl:choose>
                <xsl:when test="name() = 'def-who'">
                  <xsl:value-of select="':who'" />
                </xsl:when>
                <xsl:when test="name() = 'def-where'">
                  <xsl:value-of select="':where'" />
                </xsl:when>
                <xsl:when test="name() = 'def-thread'">
                  <xsl:value-of select="':thread'" />
                </xsl:when>
              </xsl:choose>
            </Name>
            <IsNull>0</IsNull>
            <Initials>
              <xsl:value-of select="@id" />
            </Initials>
            <Group>
              <xsl:choose>
                <xsl:when test="name() = 'def-who'">
                  <xsl:value-of select="'who'" />
                </xsl:when>
                <xsl:when test="name() = 'def-where'">
                  <xsl:value-of select="'where'" />
                </xsl:when>
                <xsl:when test="name() = 'def-thread'">
                  <xsl:value-of select="'thread'" />
                </xsl:when>
              </xsl:choose>
            </Group>
            <EmailAddress />
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <AccrueAt>3</AccrueAt>
            <Work>PT0H0M0S</Work>
            <RegularWork>PT0H0M0S</RegularWork>
            <OvertimeWork>PT0H0M0S</OvertimeWork>
            <ActualWork>PT0H0M0S</ActualWork>
            <RemainingWork>PT0H0M0S</RemainingWork>
            <ActualOvertimeWork>PT0H0M0S</ActualOvertimeWork>
            <RemainingOvertimeWork>PT0H0M0S</RemainingOvertimeWork>
            <StandardRate>0</StandardRate>
            <StandardRateFormat>3</StandardRateFormat>
            <Cost>0</Cost>
            <OvertimeRate>0</OvertimeRate>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <OvertimeCost>0</OvertimeCost>
            <CostPerUse>0</CostPerUse>
            <ActualCost>0</ActualCost>
            <ActualOvertimeCost>0</ActualOvertimeCost>
            <RemainingCost>0</RemainingCost>
            <RemainingOvertimeCost>0</RemainingOvertimeCost>
            <WorkVariance>0</WorkVariance>
            <CostVariance>0</CostVariance>
            <SV>0</SV>
            <CV>0</CV>
            <ACWP>0</ACWP>
            <CalendarUID>2</CalendarUID>
            <Notes>
              <xsl:value-of select="." />
            </Notes>
            <BCWS>0</BCWS>
            <BCWP>0</BCWP>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <ActualWorkProtected>PT0H0M0S</ActualWorkProtected>
            <ActualOvertimeWorkProtected>
            PT0H0M0S</ActualOvertimeWorkProtected>
          </Resource>
        </xsl:for-each>
      </Resources>
      <Assignments />
    </Project>
  </xsl:template>
  <!-- ******************** -->
</xsl:stylesheet>
