<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" >
 <xsl:output method="html" />
<xsl:include href="../extra.xsl"/>
 <xsl:template match="/" >
  <xsl:apply-templates mode="m0" select="content" />
 </xsl:template>
 <xsl:template mode="m0" match="content" >
  <html>
   <head>
    <meta content="Generated by Syntext XslGen v 1.1.0" name="generator" />
    <meta content="syntextxslgen" name="keywords" />
    <title>
     <xsl:value-of select="site/title" />
    </title>
    <meta content="placeholder" name="DESCRIPTION" >
     <xsl:attribute name="CONTENT" >
      <xsl:value-of select="site/meta-description" />
     </xsl:attribute>
    </meta>
    <meta content="placeholder" name="KEYWORDS" >
     <xsl:attribute name="CONTENT" >
      <xsl:value-of select="site/meta-keywords" />
     </xsl:attribute>
    </meta>
   </head>
   <body>
    <xsl:attribute name="bgcolor" >
     <xsl:value-of select="site/style/bgcolor" />
    </xsl:attribute>
    <xsl:attribute name="text" >
     <xsl:value-of select="site/style/text" />
    </xsl:attribute>
    <xsl:attribute name="link" >
     <xsl:value-of select="site/style/link" />
    </xsl:attribute>
    <xsl:attribute name="alink" >
     <xsl:value-of select="site/style/alink" />
    </xsl:attribute>
    <br/>
<!-- ************************************** -->    <hr/>
    <h1>
     <xsl:value-of select="site/title" />
    </h1>

      <xsl:value-of select="site/description" />
 
      <hr/>
    <h2>News</h2>
    <xsl:apply-templates mode="m1" select="site/news/item" />
<!-- ************************************** -->    <hr/>
    <h2>Books/Series</h2>
    <dl>
     <xsl:apply-templates mode="m2" select="book" />
    </dl>
<!-- ************************************** -->    <p>
     <img alt="hr" border="0" src="./image/rainbow_thinline.gif" />
     <img ref="hr" />
     <img>
      <xsl:attribute name="src" >
       <xsl:value-of select="key('img-index','hr')/@url" />
      </xsl:attribute>
      <xsl:attribute name="alt" >
       <xsl:value-of select="key('img-index','hr')/." />
      </xsl:attribute>
      <xsl:if test="(key('img-index','hr')/@offsite='yes')" >
       <xsl:attribute name="target" >
        <xsl:value-of select="'_blank'" />
       </xsl:attribute>
      </xsl:if>
     </img>
    </p>
    <p>URL for this page: 
       <a>
      <xsl:attribute name="href" >
       <xsl:value-of select="site/url" />
      </xsl:attribute>
      <xsl:value-of select="site/url" />
     </a>
     <br/>
    </p>
    <p>Last updated: 2003/05/26</p>
   </body>
  </html>
 </xsl:template>
 <xsl:template mode="m1" match="site/news/item" >
  <dl>
   <dt>
    <xsl:value-of select="@date" />
   </dt>
   <dd>
    <xsl:copy-of select="p" />
   </dd>
  </dl>
 </xsl:template>
 <xsl:template mode="m2" match="book" >
  <dt>
   <br/>
   <a>
    <xsl:attribute name="href" >
     <xsl:value-of select="concat(dir,'/index.html')" />
    </xsl:attribute>
    <img alt="img" border="0" src="./image/folder.png" />

         <xsl:value-of select="title" />
   </a>

     -    <xsl:value-of select="status" />

       <br/>
   <br/>
   <a ref="dynu" >
    <img ref="folder" />

         <xsl:value-of select="title" />
   </a>

     -    <xsl:value-of select="status" />

       <br/>
   <br/>
   <br/>
  </dt>
 </xsl:template>
 <xsl:template match="text()" >
  <xsl:value-of select="." />
 </xsl:template>
</xsl:stylesheet>

